services:
  - type: web
    name: expense-tracker-api
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: postgresql://expensetracker_59mr_user:kwoES61nzv1frFhltlnwD57AbpYqLgWv@dpg-cvdch3trie7s739nmha0-a.ohio-postgres.render.com/expensetracker_59mr
      - key: SPRING_DATASOURCE_USERNAME
        value: expensetracker_59mr_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: kwoES61nzv1frFhltlnwD57AbpYqLgWv
    dockerfilePath: ./Dockerfile
    autoDeploy: true
