services:
  - type: web
    name: expense-tracker-api
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql_db:3306/expense_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: user
      - key: SPRING_DATASOURCE_PASSWORD
        value: userpassword
    dockerfilePath: ./Dockerfile
    autoDeploy: true
